import logging
import os
import subprocess
import sys
import tempfile
from datetime import datetime
from typing import Optional, Dict, Any

logger = logging.getLogger(__name__)

class CadService:
    """
    Service for generating 3D CAD models using the build123d library.
    
    Allows the LLM to write Python scripts that define geometry and export to STL.
    """
    def __init__(self, db=None):
        self.db = db
        # Ensure build123d is available (will be checked at runtime if not mocked)
        try:
            from build123d import BuildPart, Box, export_stl
        except ImportError:
            logger.warning("build123d not installed. CAD generation will be unavailable.")

    async def generate_stl(self, prompt: str, script_code: str) -> Dict[str, Any]:
        """
        Execute a build123d script and return the path to the generated STL.
        
        Args:
            prompt: The user's original request.
            script_code: The Python code generated by the LLM.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        work_dir = tempfile.gettempdir()
        script_path = os.path.join(work_dir, f"cad_gen_{timestamp}.py")
        output_stl = os.path.join(work_dir, f"output_{timestamp}.stl")

        # Inject the output path into the script
        # The LLM is expected to assign the final part to 'result_part'
        full_code = f"""
from build123d import *
import numpy as np

{script_code}

if 'result_part' in locals():
    export_stl(result_part, r'{output_stl}')
else:
    raise ValueError("Script did not define 'result_part'")
"""
        
        try:
            with open(script_path, "w") as f:
                f.write(full_code)

            # Run in a subprocess for isolation
            proc = await asyncio.to_thread(
                subprocess.run,
                [sys.executable, script_path],
                capture_output=True,
                text=True,
                timeout=30
            )

            if proc.returncode != 0:
                logger.error(f"CAD generation failed: {proc.stderr}")
                return {"error": proc.stderr, "status": "failed"}

            if not os.path.exists(output_stl):
                return {"error": "STL file was not generated", "status": "failed"}

            logger.info(f"CAD generation successful: {output_stl}")
            return {
                "stl_path": output_stl,
                "status": "success",
                "prompt": prompt
            }

        except Exception as e:
            logger.error(f"Error in CAD generation: {e}")
            return {"error": str(e), "status": "failed"}
        finally:
            if os.path.exists(script_path):
                os.remove(script_path)

import asyncio
